### ISSUE TITLE
zope_cache_objects not changing?

### ISSUE THREAD

**Issue by krissik** [collective/collective.prometheus#5]
I'm wondering why `zope_cache_objects` are not changing very frequently and the value is the same for all my instances. It seems to me that it is the total amount of objects in the database and not the cached ones.

**Comment by skurfer** [comment]
Since it was originally in cache-related code, I thought it must be referring to the number of cached objects, but I could be wrong. I can’t find any documentation for `.database_size()`.

Does the number reported for you consistently match the total number of objects in your database? If so, I can give it a more accurate name and change the description.

**Comment by krissik** [comment]
Yes, it matches the "Total number of objects in the database" as shown at `/Control_Panel/Database/main/manage_cacheParameters`. I only see this number changing if I delete or add an object or pack the database.
